const PREFIX = 'posts/';

export const postActionTypes = {
    FETCH_POST_START: PREFIX + 'FETCH_POST_START',
    FETCH_POST_SUCCESS: PREFIX + 'FETCH_POST_SUCCESS',
    FETCH_POST_ERROR: PREFIX + 'FETCH_POST_ERROR'
}